import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { SocketProvider } from "@/context/SocketContext";
import { Root } from "@/components/root/Root";
const inter = Inter({ subsets: ["latin"] });
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </Head>
      <body
        className={inter.className + " w-full bg-[#F5F3F3]"}
        style={{
          overflow: "hidden",
          height: "var(--tg-viewport-stable-height)",
        }}
      >
        <SocketProvider>
          <Root>{children}</Root>
        </SocketProvider>
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
        />
        <Script
          src="https://code.createjs.com/1.0.0/preloadjs.min.js"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
